package com.example.androidtvdataport.message;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: browser_data.proto

public final class BrowserData {
  private BrowserData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code ActionCode}
   */
  public enum ActionCode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>OPEN_CINEMA_MODE = 0;</code>
     */
    OPEN_CINEMA_MODE(0),
    /**
     * <code>COCCOC_SEARCH = 1;</code>
     */
    COCCOC_SEARCH(1),
    /**
     * <code>COCCOC_INCOGNITO = 2;</code>
     */
    COCCOC_INCOGNITO(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OPEN_CINEMA_MODE = 0;</code>
     */
    public static final int OPEN_CINEMA_MODE_VALUE = 0;
    /**
     * <code>COCCOC_SEARCH = 1;</code>
     */
    public static final int COCCOC_SEARCH_VALUE = 1;
    /**
     * <code>COCCOC_INCOGNITO = 2;</code>
     */
    public static final int COCCOC_INCOGNITO_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionCode valueOf(int value) {
      return forNumber(value);
    }

    public static ActionCode forNumber(int value) {
      switch (value) {
        case 0: return OPEN_CINEMA_MODE;
        case 1: return COCCOC_SEARCH;
        case 2: return COCCOC_INCOGNITO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionCode>() {
            @java.lang.Override
            public ActionCode findValueByNumber(int number) {
              return ActionCode.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ActionCodeVerifier.INSTANCE;
    }

    private static final class ActionCodeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ActionCodeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ActionCode.forNumber(number) != null;
            }
          };

    private final int value;

    private ActionCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ActionCode)
  }

  public interface ActionCodeInjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActionCodeInject)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Code to inject
     * </pre>
     *
     * <code>.ActionCode action_code = 1;</code>
     * @return The enum numeric value on the wire for actionCode.
     */
    int getActionCodeValue();
    /**
     * <pre>
     * Code to inject
     * </pre>
     *
     * <code>.ActionCode action_code = 1;</code>
     * @return The actionCode.
     */
    BrowserData.ActionCode getActionCode();
  }
  /**
   * <pre>
   * Message to inject action code
   * </pre>
   *
   * Protobuf type {@code ActionCodeInject}
   */
  public  static final class ActionCodeInject extends
      com.google.protobuf.GeneratedMessageLite<
          ActionCodeInject, ActionCodeInject.Builder> implements
      // @@protoc_insertion_point(message_implements:ActionCodeInject)
      ActionCodeInjectOrBuilder {
    private ActionCodeInject() {
    }
    public static final int ACTION_CODE_FIELD_NUMBER = 1;
    private int actionCode_;
    /**
     * <pre>
     * Code to inject
     * </pre>
     *
     * <code>.ActionCode action_code = 1;</code>
     * @return The enum numeric value on the wire for actionCode.
     */
    @java.lang.Override
    public int getActionCodeValue() {
      return actionCode_;
    }
    /**
     * <pre>
     * Code to inject
     * </pre>
     *
     * <code>.ActionCode action_code = 1;</code>
     * @return The actionCode.
     */
    @java.lang.Override
    public BrowserData.ActionCode getActionCode() {
      BrowserData.ActionCode result = BrowserData.ActionCode.forNumber(actionCode_);
      return result == null ? BrowserData.ActionCode.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Code to inject
     * </pre>
     *
     * <code>.ActionCode action_code = 1;</code>
     * @param value The enum numeric value on the wire for actionCode to set.
     */
    private void setActionCodeValue(int value) {
        actionCode_ = value;
    }
    /**
     * <pre>
     * Code to inject
     * </pre>
     *
     * <code>.ActionCode action_code = 1;</code>
     * @param value The actionCode to set.
     */
    private void setActionCode(BrowserData.ActionCode value) {
      actionCode_ = value.getNumber();
      
    }
    /**
     * <pre>
     * Code to inject
     * </pre>
     *
     * <code>.ActionCode action_code = 1;</code>
     */
    private void clearActionCode() {
      
      actionCode_ = 0;
    }

    public static BrowserData.ActionCodeInject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.ActionCodeInject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.ActionCodeInject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.ActionCodeInject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.ActionCodeInject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.ActionCodeInject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.ActionCodeInject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.ActionCodeInject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.ActionCodeInject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static BrowserData.ActionCodeInject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.ActionCodeInject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.ActionCodeInject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(BrowserData.ActionCodeInject prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Message to inject action code
     * </pre>
     *
     * Protobuf type {@code ActionCodeInject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          BrowserData.ActionCodeInject, Builder> implements
        // @@protoc_insertion_point(builder_implements:ActionCodeInject)
        BrowserData.ActionCodeInjectOrBuilder {
      // Construct using BrowserData.ActionCodeInject.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Code to inject
       * </pre>
       *
       * <code>.ActionCode action_code = 1;</code>
       * @return The enum numeric value on the wire for actionCode.
       */
      @java.lang.Override
      public int getActionCodeValue() {
        return instance.getActionCodeValue();
      }
      /**
       * <pre>
       * Code to inject
       * </pre>
       *
       * <code>.ActionCode action_code = 1;</code>
       * @param value The actionCode to set.
       * @return This builder for chaining.
       */
      public Builder setActionCodeValue(int value) {
        copyOnWrite();
        instance.setActionCodeValue(value);
        return this;
      }
      /**
       * <pre>
       * Code to inject
       * </pre>
       *
       * <code>.ActionCode action_code = 1;</code>
       * @return The actionCode.
       */
      @java.lang.Override
      public BrowserData.ActionCode getActionCode() {
        return instance.getActionCode();
      }
      /**
       * <pre>
       * Code to inject
       * </pre>
       *
       * <code>.ActionCode action_code = 1;</code>
       * @param value The enum numeric value on the wire for actionCode to set.
       * @return This builder for chaining.
       */
      public Builder setActionCode(BrowserData.ActionCode value) {
        copyOnWrite();
        instance.setActionCode(value);
        return this;
      }
      /**
       * <pre>
       * Code to inject
       * </pre>
       *
       * <code>.ActionCode action_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearActionCode() {
        copyOnWrite();
        instance.clearActionCode();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ActionCodeInject)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new BrowserData.ActionCodeInject();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "actionCode_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<BrowserData.ActionCodeInject> parser = PARSER;
          if (parser == null) {
            synchronized (BrowserData.ActionCodeInject.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<BrowserData.ActionCodeInject>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ActionCodeInject)
    private static final BrowserData.ActionCodeInject DEFAULT_INSTANCE;
    static {
      ActionCodeInject defaultInstance = new ActionCodeInject();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ActionCodeInject.class, defaultInstance);
    }

    public static BrowserData.ActionCodeInject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ActionCodeInject> PARSER;

    public static com.google.protobuf.Parser<ActionCodeInject> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FetchDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FetchDataRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * If true, request browsing history
     * </pre>
     *
     * <code>bool fetch_history = 1;</code>
     * @return The fetchHistory.
     */
    boolean getFetchHistory();

    /**
     * <pre>
     * If true, request bookmarks
     * </pre>
     *
     * <code>bool fetch_bookmarks = 2;</code>
     * @return The fetchBookmarks.
     */
    boolean getFetchBookmarks();

    /**
     * <pre>
     * Action code to inject
     * </pre>
     *
     * <code>.ActionCodeInject action_code_inject = 3;</code>
     * @return Whether the actionCodeInject field is set.
     */
    boolean hasActionCodeInject();
    /**
     * <pre>
     * Action code to inject
     * </pre>
     *
     * <code>.ActionCodeInject action_code_inject = 3;</code>
     * @return The actionCodeInject.
     */
    BrowserData.ActionCodeInject getActionCodeInject();
  }
  /**
   * <pre>
   * Request message for fetching browser data
   * </pre>
   *
   * Protobuf type {@code FetchDataRequest}
   */
  public  static final class FetchDataRequest extends
      com.google.protobuf.GeneratedMessageLite<
          FetchDataRequest, FetchDataRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:FetchDataRequest)
      FetchDataRequestOrBuilder {
    private FetchDataRequest() {
    }
    public static final int FETCH_HISTORY_FIELD_NUMBER = 1;
    private boolean fetchHistory_;
    /**
     * <pre>
     * If true, request browsing history
     * </pre>
     *
     * <code>bool fetch_history = 1;</code>
     * @return The fetchHistory.
     */
    @java.lang.Override
    public boolean getFetchHistory() {
      return fetchHistory_;
    }
    /**
     * <pre>
     * If true, request browsing history
     * </pre>
     *
     * <code>bool fetch_history = 1;</code>
     * @param value The fetchHistory to set.
     */
    private void setFetchHistory(boolean value) {
      
      fetchHistory_ = value;
    }
    /**
     * <pre>
     * If true, request browsing history
     * </pre>
     *
     * <code>bool fetch_history = 1;</code>
     */
    private void clearFetchHistory() {
      
      fetchHistory_ = false;
    }

    public static final int FETCH_BOOKMARKS_FIELD_NUMBER = 2;
    private boolean fetchBookmarks_;
    /**
     * <pre>
     * If true, request bookmarks
     * </pre>
     *
     * <code>bool fetch_bookmarks = 2;</code>
     * @return The fetchBookmarks.
     */
    @java.lang.Override
    public boolean getFetchBookmarks() {
      return fetchBookmarks_;
    }
    /**
     * <pre>
     * If true, request bookmarks
     * </pre>
     *
     * <code>bool fetch_bookmarks = 2;</code>
     * @param value The fetchBookmarks to set.
     */
    private void setFetchBookmarks(boolean value) {
      
      fetchBookmarks_ = value;
    }
    /**
     * <pre>
     * If true, request bookmarks
     * </pre>
     *
     * <code>bool fetch_bookmarks = 2;</code>
     */
    private void clearFetchBookmarks() {
      
      fetchBookmarks_ = false;
    }

    public static final int ACTION_CODE_INJECT_FIELD_NUMBER = 3;
    private BrowserData.ActionCodeInject actionCodeInject_;
    /**
     * <pre>
     * Action code to inject
     * </pre>
     *
     * <code>.ActionCodeInject action_code_inject = 3;</code>
     */
    @java.lang.Override
    public boolean hasActionCodeInject() {
      return actionCodeInject_ != null;
    }
    /**
     * <pre>
     * Action code to inject
     * </pre>
     *
     * <code>.ActionCodeInject action_code_inject = 3;</code>
     */
    @java.lang.Override
    public BrowserData.ActionCodeInject getActionCodeInject() {
      return actionCodeInject_ == null ? BrowserData.ActionCodeInject.getDefaultInstance() : actionCodeInject_;
    }
    /**
     * <pre>
     * Action code to inject
     * </pre>
     *
     * <code>.ActionCodeInject action_code_inject = 3;</code>
     */
    private void setActionCodeInject(BrowserData.ActionCodeInject value) {
      value.getClass();
  actionCodeInject_ = value;
      
      }
    /**
     * <pre>
     * Action code to inject
     * </pre>
     *
     * <code>.ActionCodeInject action_code_inject = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeActionCodeInject(BrowserData.ActionCodeInject value) {
      value.getClass();
  if (actionCodeInject_ != null &&
          actionCodeInject_ != BrowserData.ActionCodeInject.getDefaultInstance()) {
        actionCodeInject_ =
          BrowserData.ActionCodeInject.newBuilder(actionCodeInject_).mergeFrom(value).buildPartial();
      } else {
        actionCodeInject_ = value;
      }
      
    }
    /**
     * <pre>
     * Action code to inject
     * </pre>
     *
     * <code>.ActionCodeInject action_code_inject = 3;</code>
     */
    private void clearActionCodeInject() {  actionCodeInject_ = null;
      
    }

    public static BrowserData.FetchDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static BrowserData.FetchDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(BrowserData.FetchDataRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Request message for fetching browser data
     * </pre>
     *
     * Protobuf type {@code FetchDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          BrowserData.FetchDataRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:FetchDataRequest)
        BrowserData.FetchDataRequestOrBuilder {
      // Construct using BrowserData.FetchDataRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * If true, request browsing history
       * </pre>
       *
       * <code>bool fetch_history = 1;</code>
       * @return The fetchHistory.
       */
      @java.lang.Override
      public boolean getFetchHistory() {
        return instance.getFetchHistory();
      }
      /**
       * <pre>
       * If true, request browsing history
       * </pre>
       *
       * <code>bool fetch_history = 1;</code>
       * @param value The fetchHistory to set.
       * @return This builder for chaining.
       */
      public Builder setFetchHistory(boolean value) {
        copyOnWrite();
        instance.setFetchHistory(value);
        return this;
      }
      /**
       * <pre>
       * If true, request browsing history
       * </pre>
       *
       * <code>bool fetch_history = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFetchHistory() {
        copyOnWrite();
        instance.clearFetchHistory();
        return this;
      }

      /**
       * <pre>
       * If true, request bookmarks
       * </pre>
       *
       * <code>bool fetch_bookmarks = 2;</code>
       * @return The fetchBookmarks.
       */
      @java.lang.Override
      public boolean getFetchBookmarks() {
        return instance.getFetchBookmarks();
      }
      /**
       * <pre>
       * If true, request bookmarks
       * </pre>
       *
       * <code>bool fetch_bookmarks = 2;</code>
       * @param value The fetchBookmarks to set.
       * @return This builder for chaining.
       */
      public Builder setFetchBookmarks(boolean value) {
        copyOnWrite();
        instance.setFetchBookmarks(value);
        return this;
      }
      /**
       * <pre>
       * If true, request bookmarks
       * </pre>
       *
       * <code>bool fetch_bookmarks = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFetchBookmarks() {
        copyOnWrite();
        instance.clearFetchBookmarks();
        return this;
      }

      /**
       * <pre>
       * Action code to inject
       * </pre>
       *
       * <code>.ActionCodeInject action_code_inject = 3;</code>
       */
      @java.lang.Override
      public boolean hasActionCodeInject() {
        return instance.hasActionCodeInject();
      }
      /**
       * <pre>
       * Action code to inject
       * </pre>
       *
       * <code>.ActionCodeInject action_code_inject = 3;</code>
       */
      @java.lang.Override
      public BrowserData.ActionCodeInject getActionCodeInject() {
        return instance.getActionCodeInject();
      }
      /**
       * <pre>
       * Action code to inject
       * </pre>
       *
       * <code>.ActionCodeInject action_code_inject = 3;</code>
       */
      public Builder setActionCodeInject(BrowserData.ActionCodeInject value) {
        copyOnWrite();
        instance.setActionCodeInject(value);
        return this;
        }
      /**
       * <pre>
       * Action code to inject
       * </pre>
       *
       * <code>.ActionCodeInject action_code_inject = 3;</code>
       */
      public Builder setActionCodeInject(
          BrowserData.ActionCodeInject.Builder builderForValue) {
        copyOnWrite();
        instance.setActionCodeInject(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Action code to inject
       * </pre>
       *
       * <code>.ActionCodeInject action_code_inject = 3;</code>
       */
      public Builder mergeActionCodeInject(BrowserData.ActionCodeInject value) {
        copyOnWrite();
        instance.mergeActionCodeInject(value);
        return this;
      }
      /**
       * <pre>
       * Action code to inject
       * </pre>
       *
       * <code>.ActionCodeInject action_code_inject = 3;</code>
       */
      public Builder clearActionCodeInject() {  copyOnWrite();
        instance.clearActionCodeInject();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FetchDataRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new BrowserData.FetchDataRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "fetchHistory_",
              "fetchBookmarks_",
              "actionCodeInject_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0007\u0002\u0007" +
                "\u0003\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<BrowserData.FetchDataRequest> parser = PARSER;
          if (parser == null) {
            synchronized (BrowserData.FetchDataRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<BrowserData.FetchDataRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:FetchDataRequest)
    private static final BrowserData.FetchDataRequest DEFAULT_INSTANCE;
    static {
      FetchDataRequest defaultInstance = new FetchDataRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FetchDataRequest.class, defaultInstance);
    }

    public static BrowserData.FetchDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FetchDataRequest> PARSER;

    public static com.google.protobuf.Parser<FetchDataRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FetchDataResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FetchDataResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @return The history.
     */
    java.lang.String getHistory();
    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @return The bytes for history.
     */
    com.google.protobuf.ByteString
        getHistoryBytes();

    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @return The bookmarks.
     */
    java.lang.String getBookmarks();
    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @return The bytes for bookmarks.
     */
    com.google.protobuf.ByteString
        getBookmarksBytes();

    /**
     * <pre>
     * Response to the action
     * </pre>
     *
     * <code>.ActionResponse action_response = 3;</code>
     * @return Whether the actionResponse field is set.
     */
    boolean hasActionResponse();
    /**
     * <pre>
     * Response to the action
     * </pre>
     *
     * <code>.ActionResponse action_response = 3;</code>
     * @return The actionResponse.
     */
    BrowserData.ActionResponse getActionResponse();
  }
  /**
   * <pre>
   * Response message containing browser data
   * </pre>
   *
   * Protobuf type {@code FetchDataResponse}
   */
  public  static final class FetchDataResponse extends
      com.google.protobuf.GeneratedMessageLite<
          FetchDataResponse, FetchDataResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:FetchDataResponse)
      FetchDataResponseOrBuilder {
    private FetchDataResponse() {
      history_ = "";
      bookmarks_ = "";
    }
    public static final int HISTORY_FIELD_NUMBER = 1;
    private java.lang.String history_;
    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @return The history.
     */
    @java.lang.Override
    public java.lang.String getHistory() {
      return history_;
    }
    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @return The bytes for history.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHistoryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(history_);
    }
    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @param value The history to set.
     */
    private void setHistory(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      history_ = value;
    }
    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     */
    private void clearHistory() {
      
      history_ = getDefaultInstance().getHistory();
    }
    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @param value The bytes for history to set.
     */
    private void setHistoryBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      history_ = value.toStringUtf8();
      
    }

    public static final int BOOKMARKS_FIELD_NUMBER = 2;
    private java.lang.String bookmarks_;
    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @return The bookmarks.
     */
    @java.lang.Override
    public java.lang.String getBookmarks() {
      return bookmarks_;
    }
    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @return The bytes for bookmarks.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBookmarksBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(bookmarks_);
    }
    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @param value The bookmarks to set.
     */
    private void setBookmarks(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      bookmarks_ = value;
    }
    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     */
    private void clearBookmarks() {
      
      bookmarks_ = getDefaultInstance().getBookmarks();
    }
    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @param value The bytes for bookmarks to set.
     */
    private void setBookmarksBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      bookmarks_ = value.toStringUtf8();
      
    }

    public static final int ACTION_RESPONSE_FIELD_NUMBER = 3;
    private BrowserData.ActionResponse actionResponse_;
    /**
     * <pre>
     * Response to the action
     * </pre>
     *
     * <code>.ActionResponse action_response = 3;</code>
     */
    @java.lang.Override
    public boolean hasActionResponse() {
      return actionResponse_ != null;
    }
    /**
     * <pre>
     * Response to the action
     * </pre>
     *
     * <code>.ActionResponse action_response = 3;</code>
     */
    @java.lang.Override
    public BrowserData.ActionResponse getActionResponse() {
      return actionResponse_ == null ? BrowserData.ActionResponse.getDefaultInstance() : actionResponse_;
    }
    /**
     * <pre>
     * Response to the action
     * </pre>
     *
     * <code>.ActionResponse action_response = 3;</code>
     */
    private void setActionResponse(BrowserData.ActionResponse value) {
      value.getClass();
  actionResponse_ = value;
      
      }
    /**
     * <pre>
     * Response to the action
     * </pre>
     *
     * <code>.ActionResponse action_response = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeActionResponse(BrowserData.ActionResponse value) {
      value.getClass();
  if (actionResponse_ != null &&
          actionResponse_ != BrowserData.ActionResponse.getDefaultInstance()) {
        actionResponse_ =
          BrowserData.ActionResponse.newBuilder(actionResponse_).mergeFrom(value).buildPartial();
      } else {
        actionResponse_ = value;
      }
      
    }
    /**
     * <pre>
     * Response to the action
     * </pre>
     *
     * <code>.ActionResponse action_response = 3;</code>
     */
    private void clearActionResponse() {  actionResponse_ = null;
      
    }

    public static BrowserData.FetchDataResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static BrowserData.FetchDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(BrowserData.FetchDataResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Response message containing browser data
     * </pre>
     *
     * Protobuf type {@code FetchDataResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          BrowserData.FetchDataResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:FetchDataResponse)
        BrowserData.FetchDataResponseOrBuilder {
      // Construct using BrowserData.FetchDataResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @return The history.
       */
      @java.lang.Override
      public java.lang.String getHistory() {
        return instance.getHistory();
      }
      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @return The bytes for history.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getHistoryBytes() {
        return instance.getHistoryBytes();
      }
      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @param value The history to set.
       * @return This builder for chaining.
       */
      public Builder setHistory(
          java.lang.String value) {
        copyOnWrite();
        instance.setHistory(value);
        return this;
      }
      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHistory() {
        copyOnWrite();
        instance.clearHistory();
        return this;
      }
      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @param value The bytes for history to set.
       * @return This builder for chaining.
       */
      public Builder setHistoryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHistoryBytes(value);
        return this;
      }

      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @return The bookmarks.
       */
      @java.lang.Override
      public java.lang.String getBookmarks() {
        return instance.getBookmarks();
      }
      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @return The bytes for bookmarks.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getBookmarksBytes() {
        return instance.getBookmarksBytes();
      }
      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @param value The bookmarks to set.
       * @return This builder for chaining.
       */
      public Builder setBookmarks(
          java.lang.String value) {
        copyOnWrite();
        instance.setBookmarks(value);
        return this;
      }
      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBookmarks() {
        copyOnWrite();
        instance.clearBookmarks();
        return this;
      }
      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @param value The bytes for bookmarks to set.
       * @return This builder for chaining.
       */
      public Builder setBookmarksBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBookmarksBytes(value);
        return this;
      }

      /**
       * <pre>
       * Response to the action
       * </pre>
       *
       * <code>.ActionResponse action_response = 3;</code>
       */
      @java.lang.Override
      public boolean hasActionResponse() {
        return instance.hasActionResponse();
      }
      /**
       * <pre>
       * Response to the action
       * </pre>
       *
       * <code>.ActionResponse action_response = 3;</code>
       */
      @java.lang.Override
      public BrowserData.ActionResponse getActionResponse() {
        return instance.getActionResponse();
      }
      /**
       * <pre>
       * Response to the action
       * </pre>
       *
       * <code>.ActionResponse action_response = 3;</code>
       */
      public Builder setActionResponse(BrowserData.ActionResponse value) {
        copyOnWrite();
        instance.setActionResponse(value);
        return this;
        }
      /**
       * <pre>
       * Response to the action
       * </pre>
       *
       * <code>.ActionResponse action_response = 3;</code>
       */
      public Builder setActionResponse(
          BrowserData.ActionResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setActionResponse(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Response to the action
       * </pre>
       *
       * <code>.ActionResponse action_response = 3;</code>
       */
      public Builder mergeActionResponse(BrowserData.ActionResponse value) {
        copyOnWrite();
        instance.mergeActionResponse(value);
        return this;
      }
      /**
       * <pre>
       * Response to the action
       * </pre>
       *
       * <code>.ActionResponse action_response = 3;</code>
       */
      public Builder clearActionResponse() {  copyOnWrite();
        instance.clearActionResponse();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FetchDataResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new BrowserData.FetchDataResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "history_",
              "bookmarks_",
              "actionResponse_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<BrowserData.FetchDataResponse> parser = PARSER;
          if (parser == null) {
            synchronized (BrowserData.FetchDataResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<BrowserData.FetchDataResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:FetchDataResponse)
    private static final BrowserData.FetchDataResponse DEFAULT_INSTANCE;
    static {
      FetchDataResponse defaultInstance = new FetchDataResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FetchDataResponse.class, defaultInstance);
    }

    public static BrowserData.FetchDataResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FetchDataResponse> PARSER;

    public static com.google.protobuf.Parser<FetchDataResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ActionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActionResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Status code of the action
     * </pre>
     *
     * <code>int32 status_code = 1;</code>
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <pre>
     * Message describing the action
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Message describing the action
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * Action response message
   * </pre>
   *
   * Protobuf type {@code ActionResponse}
   */
  public  static final class ActionResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ActionResponse, ActionResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:ActionResponse)
      ActionResponseOrBuilder {
    private ActionResponse() {
      message_ = "";
    }
    public static final int STATUS_CODE_FIELD_NUMBER = 1;
    private int statusCode_;
    /**
     * <pre>
     * Status code of the action
     * </pre>
     *
     * <code>int32 status_code = 1;</code>
     * @return The statusCode.
     */
    @java.lang.Override
    public int getStatusCode() {
      return statusCode_;
    }
    /**
     * <pre>
     * Status code of the action
     * </pre>
     *
     * <code>int32 status_code = 1;</code>
     * @param value The statusCode to set.
     */
    private void setStatusCode(int value) {
      
      statusCode_ = value;
    }
    /**
     * <pre>
     * Status code of the action
     * </pre>
     *
     * <code>int32 status_code = 1;</code>
     */
    private void clearStatusCode() {
      
      statusCode_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <pre>
     * Message describing the action
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <pre>
     * Message describing the action
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <pre>
     * Message describing the action
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    private void setMessage(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      message_ = value;
    }
    /**
     * <pre>
     * Message describing the action
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <pre>
     * Message describing the action
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();
      
    }

    public static BrowserData.ActionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.ActionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.ActionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.ActionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.ActionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.ActionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.ActionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.ActionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.ActionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static BrowserData.ActionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.ActionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.ActionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(BrowserData.ActionResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Action response message
     * </pre>
     *
     * Protobuf type {@code ActionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          BrowserData.ActionResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:ActionResponse)
        BrowserData.ActionResponseOrBuilder {
      // Construct using BrowserData.ActionResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Status code of the action
       * </pre>
       *
       * <code>int32 status_code = 1;</code>
       * @return The statusCode.
       */
      @java.lang.Override
      public int getStatusCode() {
        return instance.getStatusCode();
      }
      /**
       * <pre>
       * Status code of the action
       * </pre>
       *
       * <code>int32 status_code = 1;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        copyOnWrite();
        instance.setStatusCode(value);
        return this;
      }
      /**
       * <pre>
       * Status code of the action
       * </pre>
       *
       * <code>int32 status_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        copyOnWrite();
        instance.clearStatusCode();
        return this;
      }

      /**
       * <pre>
       * Message describing the action
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <pre>
       * Message describing the action
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <pre>
       * Message describing the action
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <pre>
       * Message describing the action
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <pre>
       * Message describing the action
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ActionResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new BrowserData.ActionResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "statusCode_",
              "message_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<BrowserData.ActionResponse> parser = PARSER;
          if (parser == null) {
            synchronized (BrowserData.ActionResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<BrowserData.ActionResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ActionResponse)
    private static final BrowserData.ActionResponse DEFAULT_INSTANCE;
    static {
      ActionResponse defaultInstance = new ActionResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ActionResponse.class, defaultInstance);
    }

    public static BrowserData.ActionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ActionResponse> PARSER;

    public static com.google.protobuf.Parser<ActionResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface WrapperMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WrapperMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @return The type.
     */
    BrowserData.WrapperMessage.MessageType getType();

    /**
     * <code>.FetchDataRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.FetchDataRequest request = 2;</code>
     * @return The request.
     */
    BrowserData.FetchDataRequest getRequest();

    /**
     * <code>.FetchDataResponse response = 3;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.FetchDataResponse response = 3;</code>
     * @return The response.
     */
    BrowserData.FetchDataResponse getResponse();
  }
  /**
   * <pre>
   * Wrapper message to differentiate between request and response
   * </pre>
   *
   * Protobuf type {@code WrapperMessage}
   */
  public  static final class WrapperMessage extends
      com.google.protobuf.GeneratedMessageLite<
          WrapperMessage, WrapperMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:WrapperMessage)
      WrapperMessageOrBuilder {
    private WrapperMessage() {
    }
    /**
     * Protobuf enum {@code WrapperMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>REQUEST = 0;</code>
       */
      REQUEST(0),
      /**
       * <code>RESPONSE = 1;</code>
       */
      RESPONSE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>REQUEST = 0;</code>
       */
      public static final int REQUEST_VALUE = 0;
      /**
       * <code>RESPONSE = 1;</code>
       */
      public static final int RESPONSE_VALUE = 1;


      @java.lang.Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              @java.lang.Override
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return MessageTypeVerifier.INSTANCE;
      }

      private static final class MessageTypeVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new MessageTypeVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return MessageType.forNumber(number) != null;
              }
            };

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:WrapperMessage.MessageType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public BrowserData.WrapperMessage.MessageType getType() {
      BrowserData.WrapperMessage.MessageType result = BrowserData.WrapperMessage.MessageType.forNumber(type_);
      return result == null ? BrowserData.WrapperMessage.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @param value The type to set.
     */
    private void setType(BrowserData.WrapperMessage.MessageType value) {
      type_ = value.getNumber();
      
    }
    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     */
    private void clearType() {
      
      type_ = 0;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private BrowserData.FetchDataRequest request_;
    /**
     * <code>.FetchDataRequest request = 2;</code>
     */
    @java.lang.Override
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.FetchDataRequest request = 2;</code>
     */
    @java.lang.Override
    public BrowserData.FetchDataRequest getRequest() {
      return request_ == null ? BrowserData.FetchDataRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>.FetchDataRequest request = 2;</code>
     */
    private void setRequest(BrowserData.FetchDataRequest value) {
      value.getClass();
  request_ = value;
      
      }
    /**
     * <code>.FetchDataRequest request = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeRequest(BrowserData.FetchDataRequest value) {
      value.getClass();
  if (request_ != null &&
          request_ != BrowserData.FetchDataRequest.getDefaultInstance()) {
        request_ =
          BrowserData.FetchDataRequest.newBuilder(request_).mergeFrom(value).buildPartial();
      } else {
        request_ = value;
      }
      
    }
    /**
     * <code>.FetchDataRequest request = 2;</code>
     */
    private void clearRequest() {  request_ = null;
      
    }

    public static final int RESPONSE_FIELD_NUMBER = 3;
    private BrowserData.FetchDataResponse response_;
    /**
     * <code>.FetchDataResponse response = 3;</code>
     */
    @java.lang.Override
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.FetchDataResponse response = 3;</code>
     */
    @java.lang.Override
    public BrowserData.FetchDataResponse getResponse() {
      return response_ == null ? BrowserData.FetchDataResponse.getDefaultInstance() : response_;
    }
    /**
     * <code>.FetchDataResponse response = 3;</code>
     */
    private void setResponse(BrowserData.FetchDataResponse value) {
      value.getClass();
  response_ = value;
      
      }
    /**
     * <code>.FetchDataResponse response = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeResponse(BrowserData.FetchDataResponse value) {
      value.getClass();
  if (response_ != null &&
          response_ != BrowserData.FetchDataResponse.getDefaultInstance()) {
        response_ =
          BrowserData.FetchDataResponse.newBuilder(response_).mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      
    }
    /**
     * <code>.FetchDataResponse response = 3;</code>
     */
    private void clearResponse() {  response_ = null;
      
    }

    public static BrowserData.WrapperMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.WrapperMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.WrapperMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BrowserData.WrapperMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.WrapperMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static BrowserData.WrapperMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BrowserData.WrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(BrowserData.WrapperMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Wrapper message to differentiate between request and response
     * </pre>
     *
     * Protobuf type {@code WrapperMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          BrowserData.WrapperMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:WrapperMessage)
        BrowserData.WrapperMessageOrBuilder {
      // Construct using BrowserData.WrapperMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public BrowserData.WrapperMessage.MessageType getType() {
        return instance.getType();
      }
      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(BrowserData.WrapperMessage.MessageType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      @java.lang.Override
      public boolean hasRequest() {
        return instance.hasRequest();
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      @java.lang.Override
      public BrowserData.FetchDataRequest getRequest() {
        return instance.getRequest();
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public Builder setRequest(BrowserData.FetchDataRequest value) {
        copyOnWrite();
        instance.setRequest(value);
        return this;
        }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public Builder setRequest(
          BrowserData.FetchDataRequest.Builder builderForValue) {
        copyOnWrite();
        instance.setRequest(builderForValue.build());
        return this;
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public Builder mergeRequest(BrowserData.FetchDataRequest value) {
        copyOnWrite();
        instance.mergeRequest(value);
        return this;
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public Builder clearRequest() {  copyOnWrite();
        instance.clearRequest();
        return this;
      }

      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      @java.lang.Override
      public boolean hasResponse() {
        return instance.hasResponse();
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      @java.lang.Override
      public BrowserData.FetchDataResponse getResponse() {
        return instance.getResponse();
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public Builder setResponse(BrowserData.FetchDataResponse value) {
        copyOnWrite();
        instance.setResponse(value);
        return this;
        }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public Builder setResponse(
          BrowserData.FetchDataResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setResponse(builderForValue.build());
        return this;
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public Builder mergeResponse(BrowserData.FetchDataResponse value) {
        copyOnWrite();
        instance.mergeResponse(value);
        return this;
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public Builder clearResponse() {  copyOnWrite();
        instance.clearResponse();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WrapperMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new BrowserData.WrapperMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "type_",
              "request_",
              "response_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\t\u0003" +
                "\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<BrowserData.WrapperMessage> parser = PARSER;
          if (parser == null) {
            synchronized (BrowserData.WrapperMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<BrowserData.WrapperMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:WrapperMessage)
    private static final BrowserData.WrapperMessage DEFAULT_INSTANCE;
    static {
      WrapperMessage defaultInstance = new WrapperMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WrapperMessage.class, defaultInstance);
    }

    public static BrowserData.WrapperMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WrapperMessage> PARSER;

    public static com.google.protobuf.Parser<WrapperMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
