package com.example.androidtvdataport.message;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: browser_data.proto

public final class BrowserData {
  private BrowserData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FetchDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FetchDataRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * If true, request browsing history
     * </pre>
     *
     * <code>bool fetch_history = 1;</code>
     * @return The fetchHistory.
     */
    boolean getFetchHistory();

    /**
     * <pre>
     * If true, request bookmarks
     * </pre>
     *
     * <code>bool fetch_bookmarks = 2;</code>
     * @return The fetchBookmarks.
     */
    boolean getFetchBookmarks();
  }
  /**
   * <pre>
   * Request message for fetching browser data
   * </pre>
   *
   * Protobuf type {@code FetchDataRequest}
   */
  public static final class FetchDataRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FetchDataRequest)
      FetchDataRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FetchDataRequest.newBuilder() to construct.
    private FetchDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FetchDataRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FetchDataRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FetchDataRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              fetchHistory_ = input.readBool();
              break;
            }
            case 16: {

              fetchBookmarks_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BrowserData.internal_static_FetchDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BrowserData.internal_static_FetchDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BrowserData.FetchDataRequest.class, BrowserData.FetchDataRequest.Builder.class);
    }

    public static final int FETCH_HISTORY_FIELD_NUMBER = 1;
    private boolean fetchHistory_;
    /**
     * <pre>
     * If true, request browsing history
     * </pre>
     *
     * <code>bool fetch_history = 1;</code>
     * @return The fetchHistory.
     */
    @java.lang.Override
    public boolean getFetchHistory() {
      return fetchHistory_;
    }

    public static final int FETCH_BOOKMARKS_FIELD_NUMBER = 2;
    private boolean fetchBookmarks_;
    /**
     * <pre>
     * If true, request bookmarks
     * </pre>
     *
     * <code>bool fetch_bookmarks = 2;</code>
     * @return The fetchBookmarks.
     */
    @java.lang.Override
    public boolean getFetchBookmarks() {
      return fetchBookmarks_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fetchHistory_ != false) {
        output.writeBool(1, fetchHistory_);
      }
      if (fetchBookmarks_ != false) {
        output.writeBool(2, fetchBookmarks_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fetchHistory_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, fetchHistory_);
      }
      if (fetchBookmarks_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, fetchBookmarks_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BrowserData.FetchDataRequest)) {
        return super.equals(obj);
      }
      BrowserData.FetchDataRequest other = (BrowserData.FetchDataRequest) obj;

      if (getFetchHistory()
          != other.getFetchHistory()) return false;
      if (getFetchBookmarks()
          != other.getFetchBookmarks()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FETCH_HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFetchHistory());
      hash = (37 * hash) + FETCH_BOOKMARKS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFetchBookmarks());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BrowserData.FetchDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BrowserData.FetchDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BrowserData.FetchDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BrowserData.FetchDataRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request message for fetching browser data
     * </pre>
     *
     * Protobuf type {@code FetchDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FetchDataRequest)
        BrowserData.FetchDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BrowserData.internal_static_FetchDataRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BrowserData.internal_static_FetchDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BrowserData.FetchDataRequest.class, BrowserData.FetchDataRequest.Builder.class);
      }

      // Construct using BrowserData.FetchDataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fetchHistory_ = false;

        fetchBookmarks_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BrowserData.internal_static_FetchDataRequest_descriptor;
      }

      @java.lang.Override
      public BrowserData.FetchDataRequest getDefaultInstanceForType() {
        return BrowserData.FetchDataRequest.getDefaultInstance();
      }

      @java.lang.Override
      public BrowserData.FetchDataRequest build() {
        BrowserData.FetchDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BrowserData.FetchDataRequest buildPartial() {
        BrowserData.FetchDataRequest result = new BrowserData.FetchDataRequest(this);
        result.fetchHistory_ = fetchHistory_;
        result.fetchBookmarks_ = fetchBookmarks_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BrowserData.FetchDataRequest) {
          return mergeFrom((BrowserData.FetchDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BrowserData.FetchDataRequest other) {
        if (other == BrowserData.FetchDataRequest.getDefaultInstance()) return this;
        if (other.getFetchHistory() != false) {
          setFetchHistory(other.getFetchHistory());
        }
        if (other.getFetchBookmarks() != false) {
          setFetchBookmarks(other.getFetchBookmarks());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BrowserData.FetchDataRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BrowserData.FetchDataRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean fetchHistory_ ;
      /**
       * <pre>
       * If true, request browsing history
       * </pre>
       *
       * <code>bool fetch_history = 1;</code>
       * @return The fetchHistory.
       */
      @java.lang.Override
      public boolean getFetchHistory() {
        return fetchHistory_;
      }
      /**
       * <pre>
       * If true, request browsing history
       * </pre>
       *
       * <code>bool fetch_history = 1;</code>
       * @param value The fetchHistory to set.
       * @return This builder for chaining.
       */
      public Builder setFetchHistory(boolean value) {
        
        fetchHistory_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If true, request browsing history
       * </pre>
       *
       * <code>bool fetch_history = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFetchHistory() {
        
        fetchHistory_ = false;
        onChanged();
        return this;
      }

      private boolean fetchBookmarks_ ;
      /**
       * <pre>
       * If true, request bookmarks
       * </pre>
       *
       * <code>bool fetch_bookmarks = 2;</code>
       * @return The fetchBookmarks.
       */
      @java.lang.Override
      public boolean getFetchBookmarks() {
        return fetchBookmarks_;
      }
      /**
       * <pre>
       * If true, request bookmarks
       * </pre>
       *
       * <code>bool fetch_bookmarks = 2;</code>
       * @param value The fetchBookmarks to set.
       * @return This builder for chaining.
       */
      public Builder setFetchBookmarks(boolean value) {
        
        fetchBookmarks_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If true, request bookmarks
       * </pre>
       *
       * <code>bool fetch_bookmarks = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFetchBookmarks() {
        
        fetchBookmarks_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FetchDataRequest)
    }

    // @@protoc_insertion_point(class_scope:FetchDataRequest)
    private static final BrowserData.FetchDataRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BrowserData.FetchDataRequest();
    }

    public static BrowserData.FetchDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FetchDataRequest>
        PARSER = new com.google.protobuf.AbstractParser<FetchDataRequest>() {
      @java.lang.Override
      public FetchDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchDataRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FetchDataRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FetchDataRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BrowserData.FetchDataRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FetchDataResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FetchDataResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @return The history.
     */
    java.lang.String getHistory();
    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @return The bytes for history.
     */
    com.google.protobuf.ByteString
        getHistoryBytes();

    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @return The bookmarks.
     */
    java.lang.String getBookmarks();
    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @return The bytes for bookmarks.
     */
    com.google.protobuf.ByteString
        getBookmarksBytes();
  }
  /**
   * <pre>
   * Response message containing browser data
   * </pre>
   *
   * Protobuf type {@code FetchDataResponse}
   */
  public static final class FetchDataResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FetchDataResponse)
      FetchDataResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FetchDataResponse.newBuilder() to construct.
    private FetchDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FetchDataResponse() {
      history_ = "";
      bookmarks_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FetchDataResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FetchDataResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              history_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              bookmarks_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BrowserData.internal_static_FetchDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BrowserData.internal_static_FetchDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BrowserData.FetchDataResponse.class, BrowserData.FetchDataResponse.Builder.class);
    }

    public static final int HISTORY_FIELD_NUMBER = 1;
    private volatile java.lang.Object history_;
    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @return The history.
     */
    @java.lang.Override
    public java.lang.String getHistory() {
      java.lang.Object ref = history_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        history_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Browsing history data as a string
     * </pre>
     *
     * <code>string history = 1;</code>
     * @return The bytes for history.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHistoryBytes() {
      java.lang.Object ref = history_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        history_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOKMARKS_FIELD_NUMBER = 2;
    private volatile java.lang.Object bookmarks_;
    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @return The bookmarks.
     */
    @java.lang.Override
    public java.lang.String getBookmarks() {
      java.lang.Object ref = bookmarks_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bookmarks_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Bookmarks data as a string
     * </pre>
     *
     * <code>string bookmarks = 2;</code>
     * @return The bytes for bookmarks.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBookmarksBytes() {
      java.lang.Object ref = bookmarks_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookmarks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(history_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, history_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bookmarks_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bookmarks_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(history_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, history_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bookmarks_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bookmarks_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BrowserData.FetchDataResponse)) {
        return super.equals(obj);
      }
      BrowserData.FetchDataResponse other = (BrowserData.FetchDataResponse) obj;

      if (!getHistory()
          .equals(other.getHistory())) return false;
      if (!getBookmarks()
          .equals(other.getBookmarks())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getHistory().hashCode();
      hash = (37 * hash) + BOOKMARKS_FIELD_NUMBER;
      hash = (53 * hash) + getBookmarks().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BrowserData.FetchDataResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BrowserData.FetchDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BrowserData.FetchDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BrowserData.FetchDataResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response message containing browser data
     * </pre>
     *
     * Protobuf type {@code FetchDataResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FetchDataResponse)
        BrowserData.FetchDataResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BrowserData.internal_static_FetchDataResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BrowserData.internal_static_FetchDataResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BrowserData.FetchDataResponse.class, BrowserData.FetchDataResponse.Builder.class);
      }

      // Construct using BrowserData.FetchDataResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        history_ = "";

        bookmarks_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BrowserData.internal_static_FetchDataResponse_descriptor;
      }

      @java.lang.Override
      public BrowserData.FetchDataResponse getDefaultInstanceForType() {
        return BrowserData.FetchDataResponse.getDefaultInstance();
      }

      @java.lang.Override
      public BrowserData.FetchDataResponse build() {
        BrowserData.FetchDataResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BrowserData.FetchDataResponse buildPartial() {
        BrowserData.FetchDataResponse result = new BrowserData.FetchDataResponse(this);
        result.history_ = history_;
        result.bookmarks_ = bookmarks_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BrowserData.FetchDataResponse) {
          return mergeFrom((BrowserData.FetchDataResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BrowserData.FetchDataResponse other) {
        if (other == BrowserData.FetchDataResponse.getDefaultInstance()) return this;
        if (!other.getHistory().isEmpty()) {
          history_ = other.history_;
          onChanged();
        }
        if (!other.getBookmarks().isEmpty()) {
          bookmarks_ = other.bookmarks_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BrowserData.FetchDataResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BrowserData.FetchDataResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object history_ = "";
      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @return The history.
       */
      public java.lang.String getHistory() {
        java.lang.Object ref = history_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          history_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @return The bytes for history.
       */
      public com.google.protobuf.ByteString
          getHistoryBytes() {
        java.lang.Object ref = history_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          history_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @param value The history to set.
       * @return This builder for chaining.
       */
      public Builder setHistory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        history_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHistory() {
        
        history_ = getDefaultInstance().getHistory();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Browsing history data as a string
       * </pre>
       *
       * <code>string history = 1;</code>
       * @param value The bytes for history to set.
       * @return This builder for chaining.
       */
      public Builder setHistoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        history_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bookmarks_ = "";
      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @return The bookmarks.
       */
      public java.lang.String getBookmarks() {
        java.lang.Object ref = bookmarks_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bookmarks_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @return The bytes for bookmarks.
       */
      public com.google.protobuf.ByteString
          getBookmarksBytes() {
        java.lang.Object ref = bookmarks_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookmarks_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @param value The bookmarks to set.
       * @return This builder for chaining.
       */
      public Builder setBookmarks(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bookmarks_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBookmarks() {
        
        bookmarks_ = getDefaultInstance().getBookmarks();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Bookmarks data as a string
       * </pre>
       *
       * <code>string bookmarks = 2;</code>
       * @param value The bytes for bookmarks to set.
       * @return This builder for chaining.
       */
      public Builder setBookmarksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bookmarks_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FetchDataResponse)
    }

    // @@protoc_insertion_point(class_scope:FetchDataResponse)
    private static final BrowserData.FetchDataResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BrowserData.FetchDataResponse();
    }

    public static BrowserData.FetchDataResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FetchDataResponse>
        PARSER = new com.google.protobuf.AbstractParser<FetchDataResponse>() {
      @java.lang.Override
      public FetchDataResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchDataResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FetchDataResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FetchDataResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BrowserData.FetchDataResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WrapperMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WrapperMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @return The type.
     */
    BrowserData.WrapperMessage.MessageType getType();

    /**
     * <code>.FetchDataRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.FetchDataRequest request = 2;</code>
     * @return The request.
     */
    BrowserData.FetchDataRequest getRequest();
    /**
     * <code>.FetchDataRequest request = 2;</code>
     */
    BrowserData.FetchDataRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>.FetchDataResponse response = 3;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.FetchDataResponse response = 3;</code>
     * @return The response.
     */
    BrowserData.FetchDataResponse getResponse();
    /**
     * <code>.FetchDataResponse response = 3;</code>
     */
    BrowserData.FetchDataResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * <pre>
   * Wrapper message to differentiate between request and response
   * </pre>
   *
   * Protobuf type {@code WrapperMessage}
   */
  public static final class WrapperMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WrapperMessage)
      WrapperMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WrapperMessage.newBuilder() to construct.
    private WrapperMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WrapperMessage() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WrapperMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WrapperMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              BrowserData.FetchDataRequest.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(BrowserData.FetchDataRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              BrowserData.FetchDataResponse.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(BrowserData.FetchDataResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BrowserData.internal_static_WrapperMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BrowserData.internal_static_WrapperMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BrowserData.WrapperMessage.class, BrowserData.WrapperMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code WrapperMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQUEST = 0;</code>
       */
      REQUEST(0),
      /**
       * <code>RESPONSE = 1;</code>
       */
      RESPONSE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>REQUEST = 0;</code>
       */
      public static final int REQUEST_VALUE = 0;
      /**
       * <code>RESPONSE = 1;</code>
       */
      public static final int RESPONSE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return BrowserData.WrapperMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:WrapperMessage.MessageType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.WrapperMessage.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public BrowserData.WrapperMessage.MessageType getType() {
      @SuppressWarnings("deprecation")
      BrowserData.WrapperMessage.MessageType result = BrowserData.WrapperMessage.MessageType.valueOf(type_);
      return result == null ? BrowserData.WrapperMessage.MessageType.UNRECOGNIZED : result;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private BrowserData.FetchDataRequest request_;
    /**
     * <code>.FetchDataRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.FetchDataRequest request = 2;</code>
     * @return The request.
     */
    @java.lang.Override
    public BrowserData.FetchDataRequest getRequest() {
      return request_ == null ? BrowserData.FetchDataRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>.FetchDataRequest request = 2;</code>
     */
    @java.lang.Override
    public BrowserData.FetchDataRequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int RESPONSE_FIELD_NUMBER = 3;
    private BrowserData.FetchDataResponse response_;
    /**
     * <code>.FetchDataResponse response = 3;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.FetchDataResponse response = 3;</code>
     * @return The response.
     */
    @java.lang.Override
    public BrowserData.FetchDataResponse getResponse() {
      return response_ == null ? BrowserData.FetchDataResponse.getDefaultInstance() : response_;
    }
    /**
     * <code>.FetchDataResponse response = 3;</code>
     */
    @java.lang.Override
    public BrowserData.FetchDataResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != BrowserData.WrapperMessage.MessageType.REQUEST.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (request_ != null) {
        output.writeMessage(2, getRequest());
      }
      if (response_ != null) {
        output.writeMessage(3, getResponse());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != BrowserData.WrapperMessage.MessageType.REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRequest());
      }
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BrowserData.WrapperMessage)) {
        return super.equals(obj);
      }
      BrowserData.WrapperMessage other = (BrowserData.WrapperMessage) obj;

      if (type_ != other.type_) return false;
      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BrowserData.WrapperMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BrowserData.WrapperMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BrowserData.WrapperMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BrowserData.WrapperMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BrowserData.WrapperMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BrowserData.WrapperMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BrowserData.WrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BrowserData.WrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BrowserData.WrapperMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Wrapper message to differentiate between request and response
     * </pre>
     *
     * Protobuf type {@code WrapperMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WrapperMessage)
        BrowserData.WrapperMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BrowserData.internal_static_WrapperMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BrowserData.internal_static_WrapperMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BrowserData.WrapperMessage.class, BrowserData.WrapperMessage.Builder.class);
      }

      // Construct using BrowserData.WrapperMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BrowserData.internal_static_WrapperMessage_descriptor;
      }

      @java.lang.Override
      public BrowserData.WrapperMessage getDefaultInstanceForType() {
        return BrowserData.WrapperMessage.getDefaultInstance();
      }

      @java.lang.Override
      public BrowserData.WrapperMessage build() {
        BrowserData.WrapperMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BrowserData.WrapperMessage buildPartial() {
        BrowserData.WrapperMessage result = new BrowserData.WrapperMessage(this);
        result.type_ = type_;
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BrowserData.WrapperMessage) {
          return mergeFrom((BrowserData.WrapperMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BrowserData.WrapperMessage other) {
        if (other == BrowserData.WrapperMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BrowserData.WrapperMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BrowserData.WrapperMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public BrowserData.WrapperMessage.MessageType getType() {
        @SuppressWarnings("deprecation")
        BrowserData.WrapperMessage.MessageType result = BrowserData.WrapperMessage.MessageType.valueOf(type_);
        return result == null ? BrowserData.WrapperMessage.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(BrowserData.WrapperMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.WrapperMessage.MessageType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private BrowserData.FetchDataRequest request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          BrowserData.FetchDataRequest, BrowserData.FetchDataRequest.Builder, BrowserData.FetchDataRequestOrBuilder> requestBuilder_;
      /**
       * <code>.FetchDataRequest request = 2;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       * @return The request.
       */
      public BrowserData.FetchDataRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? BrowserData.FetchDataRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public Builder setRequest(BrowserData.FetchDataRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public Builder setRequest(
          BrowserData.FetchDataRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public Builder mergeRequest(BrowserData.FetchDataRequest value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              BrowserData.FetchDataRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public BrowserData.FetchDataRequest.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      public BrowserData.FetchDataRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              BrowserData.FetchDataRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.FetchDataRequest request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          BrowserData.FetchDataRequest, BrowserData.FetchDataRequest.Builder, BrowserData.FetchDataRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              BrowserData.FetchDataRequest, BrowserData.FetchDataRequest.Builder, BrowserData.FetchDataRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private BrowserData.FetchDataResponse response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          BrowserData.FetchDataResponse, BrowserData.FetchDataResponse.Builder, BrowserData.FetchDataResponseOrBuilder> responseBuilder_;
      /**
       * <code>.FetchDataResponse response = 3;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       * @return The response.
       */
      public BrowserData.FetchDataResponse getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? BrowserData.FetchDataResponse.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public Builder setResponse(BrowserData.FetchDataResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public Builder setResponse(
          BrowserData.FetchDataResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public Builder mergeResponse(BrowserData.FetchDataResponse value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              BrowserData.FetchDataResponse.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public BrowserData.FetchDataResponse.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      public BrowserData.FetchDataResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              BrowserData.FetchDataResponse.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.FetchDataResponse response = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          BrowserData.FetchDataResponse, BrowserData.FetchDataResponse.Builder, BrowserData.FetchDataResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              BrowserData.FetchDataResponse, BrowserData.FetchDataResponse.Builder, BrowserData.FetchDataResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WrapperMessage)
    }

    // @@protoc_insertion_point(class_scope:WrapperMessage)
    private static final BrowserData.WrapperMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BrowserData.WrapperMessage();
    }

    public static BrowserData.WrapperMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WrapperMessage>
        PARSER = new com.google.protobuf.AbstractParser<WrapperMessage>() {
      @java.lang.Override
      public WrapperMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WrapperMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WrapperMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WrapperMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BrowserData.WrapperMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchDataRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FetchDataRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchDataResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FetchDataResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WrapperMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WrapperMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022browser_data.proto\"B\n\020FetchDataRequest" +
      "\022\025\n\rfetch_history\030\001 \001(\010\022\027\n\017fetch_bookmar" +
      "ks\030\002 \001(\010\"7\n\021FetchDataResponse\022\017\n\007history" +
      "\030\001 \001(\t\022\021\n\tbookmarks\030\002 \001(\t\"\257\001\n\016WrapperMes" +
      "sage\022)\n\004type\030\001 \001(\0162\033.WrapperMessage.Mess" +
      "ageType\022\"\n\007request\030\002 \001(\0132\021.FetchDataRequ" +
      "est\022$\n\010response\030\003 \001(\0132\022.FetchDataRespons" +
      "e\"(\n\013MessageType\022\013\n\007REQUEST\020\000\022\014\n\010RESPONS" +
      "E\020\0012H\n\022BrowserDataService\0222\n\tFetchData\022\021" +
      ".FetchDataRequest\032\022.FetchDataResponseb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FetchDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FetchDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FetchDataRequest_descriptor,
        new java.lang.String[] { "FetchHistory", "FetchBookmarks", });
    internal_static_FetchDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FetchDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FetchDataResponse_descriptor,
        new java.lang.String[] { "History", "Bookmarks", });
    internal_static_WrapperMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WrapperMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WrapperMessage_descriptor,
        new java.lang.String[] { "Type", "Request", "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
